version: '2'

services:

  viper:
    container_name: viper
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/app/
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
